-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgywM/jSnHTCr4/alM
6a6syJdEgdAqXmbxvgYDRKihICegCgYIKoZIzj0DAQehRANCAAQ1tfV7ZWRlfoI0
SjVj8SGcNv8Ruq6xS/Dmo5X2Uc3ztfgRefOvd/A5wh6ZF8P2mPCkFHrxC42HkhG0
IoExyajV
-----END PRIVATE KEY-----